# frozen_string_literal: true

require "rake/extensiontask"

Rake::ExtensionTask.new("native") do |extension|
  extension.lib_dir = "lib/klenod/plugin/css"
  extension.ext_dir = "ext/native"
end

task default: :compile
