[segments]
about = "om"
api = "api"
assets = "assets"
blog = "blogg"
dashboard = "instrumentpanel"
data = "data"
demo = "demo"
docs = "dokument"
feed = "flode"
forms = "formular"
hybrid = "hybrid"
login = "logga-in"
markdown = "markdown"
photo = "foto"
profile = "profil"
routing = "routning"
settings = "installningar"
shop = "butik"
