[segments]
about = "about"
api = "api"
assets = "assets"
blog = "blog"
dashboard = "dashboard"
data = "data"
demo = "demo"
docs = "docs"
feed = "feed"
forms = "forms"
hybrid = "hybrid"
login = "login"
markdown = "markdown"
photo = "photo"
profile = "profile"
routing = "routing"
settings = "settings"
shop = "shop"
