[segments]
about = "om"
api = "api"
assets = "assets"
blog = "blogg"
dashboard = "instrumentpanel"
data = "data"
demo = "demo"
development = "utveckling"
docs = "dokument"
feed = "flode"
forms = "formular"
getting-started = "kom-igang"
hybrid = "hybrid"
login = "logga-in"
markdown = "markdown"
module-graph = "modulgraf"
photo = "foto"
plugins = "plugins"
profile = "profil"
routing = "routning"
settings = "installningar"
shop = "butik"
templates = "mallar"
build-runtime = "bygge-runtime"
configuration = "konfiguration"
core-concepts = "grundkoncept"
haml-components = "haml-komponenter"
