[segments]
about = "om"
api = "api"
assets = "tillgangar"
blog = "blogg"
dashboard = "instrumentpanel"
data = "data"
demo = "demo"
docs = "dokument"
feed = "flode"
forms = "formular"
hybrid = "hybrid"
login = "logga-in"
photo = "foto"
profile = "profil"
routing = "ruttning"
settings = "installningar"
shop = "butik"
