[segments]
about = "about"
api = "api"
assets = "assets"
blog = "blog"
dashboard = "dashboard"
data = "data"
demo = "demo"
development = "development"
docs = "docs"
feed = "feed"
forms = "forms"
getting-started = "getting-started"
hybrid = "hybrid"
login = "login"
markdown = "markdown"
module-graph = "module-graph"
photo = "photo"
plugins = "plugins"
profile = "profile"
routing = "routing"
settings = "settings"
shop = "shop"
templates = "templates"
build-runtime = "build-runtime"
configuration = "configuration"
core-concepts = "core-concepts"
haml-components = "haml-components"
