[tabs]
overview = "Översikt"
assets = "Assets"
forms = "Formulär"
dashboard = "Instrumentpanel"
blog = "Blogg"
data = "Dataimport"
markdown = "Markdown"
javascript = "JavaScript"
hybrid = "Hybridroute"
routing = "Routning"
dynamic_params = "Dynamiska parametrar"
catch_all = "Catch-all"
