# frozen_string_literal: true

source "https://rubygems.org"

gem "klenod-runtime", path: "../../gems/klenod-runtime"
gem "klenod-rack", path: "../../gems/klenod-rack"
gem "async-http", "~> 0.95.1"
gem "http-accept", "~> 2.2"
gem "localhost", "~> 1.8"
gem "rbnacl", "~> 7.1"
gem "rouge", "~> 5.0"

group :development, :build do
  gem "minitest", "~> 6.0"
  gem "nokolexbor"
  gem "klenod", path: "../../gems/klenod"
  gem "klenod-build", path: "../../gems/klenod-build"
  gem "klenod-plugin-css", path: "../../gems/klenod-plugin-css"
  gem "klenod-plugin-javascript", path: "../../gems/klenod-plugin-javascript"
  gem "vernier"
end
