# frozen_string_literal: true

source "https://rubygems.org"

gem "klenod", path: "../../gems/klenod"
gem "klenod-runtime", path: "../../gems/klenod-runtime"
gem "klenod-build", path: "../../gems/klenod-build"
gem "klenod-rack", path: "../../gems/klenod-rack"
gem "rbnacl", "~> 7.1"
