# frozen_string_literal: true

source "https://rubygems.org"

gem "klenod-runtime", path: "../../gems/klenod-runtime"
gem "klenod-rack", path: "../../gems/klenod-rack"
gem "rbnacl", "~> 7.1"
gem "rouge", "~> 5.0"

group :development, :build do
  gem "minitest", "~> 6.0"
  gem "klenod", path: "../../gems/klenod"
  gem "klenod-build", path: "../../gems/klenod-build"
  gem "vernier"
end

gem "http-accept", "~> 2.2"

gem "localhost", "~> 1.8"
